name: Build APK FIXED FINAL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install cython buildozer

    - name: Initialize buildozer (NO ROOT FIX)
      run: |
        buildozer init || true

    - name: Fix permissions
      run: |
        sudo chown -R $USER:$USER .

    - name: Build APK (FORCE NON-INTERACTIVE)
      run: |
        export PIP_NO_INPUT=1
        export DEBIAN_FRONTEND=noninteractive
        yes | buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: "**/*.apk"
